/**
 * AgentHandover Observer — Viewport-Bounded DOM Snapshot Capture
 *
 * Captures a semantic DOM tree of all elements currently visible within the
 * browser viewport.  The snapshot is designed for downstream workflow learning,
 * not pixel-perfect rendering — so we extract semantic anchors (ARIA labels,
 * roles, data-testid, visible innerText, bounding boxes) and deliberately
 * strip generated/hashed CSS class names ("CSS rot") that change across
 * builds and are useless for pattern matching.
 *
 * Key capabilities:
 *   - Viewport filtering via getBoundingClientRect()
 *   - Shadow DOM piercing (recursive traversal into open shadowRoots)
 *   - Table truncation (max 50 visible rows + buffer)
 *   - Long-text truncation (max 500 chars)
 *   - CSS rot stripping (Emotion, styled-components, CSS Modules, generic hashed classes)
 *   - Semantic anchor extraction (role, aria-label, data-testid, innerText, bbox)
 *   - Interactive element state capture (enabled, checked, selected)
 */

import type { DomNode } from './types';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Maximum number of table rows to include in a snapshot. */
export const MAX_TABLE_ROWS = 50;

/** Maximum character length for innerText on any single node. */
export const MAX_TEXT_LENGTH = 500;

/** Maximum character length for input/textarea values.
 *  Higher than MAX_TEXT_LENGTH because user-produced text is the most
 *  valuable signal for workflow learning and future fine-tuning. */
export const MAX_INPUT_TEXT_LENGTH = 2000;

/** Maximum recursion depth when walking the DOM tree. */
export const MAX_TREE_DEPTH = 30;

/** Maximum total node count in a single snapshot.
 *  Prevents oversized NM messages from heavy pages (e.g. Google Sheets). */
export const MAX_NODE_COUNT = 3000;

/** Minimum element dimension in pixels; elements smaller are filtered out. */
export const MIN_ELEMENT_SIZE = 1;

// ---------------------------------------------------------------------------
// CSS Rot Detection Patterns
// ---------------------------------------------------------------------------

/**
 * Patterns that match auto-generated / hashed CSS class names.
 * These classes change across builds and carry no semantic meaning,
 * so we strip them from the snapshot.
 *
 * Each entry has a human-readable label (for debugging) and a RegExp.
 */
const CSS_ROT_PATTERNS: ReadonlyArray<{ label: string; pattern: RegExp }> = [
  // Emotion:  css-1a2b3c, css-0
  { label: 'emotion', pattern: /^css-[a-z0-9]+$/ },

  // styled-components:  sc-bdfBjE, sc-abc123
  { label: 'styled-components', pattern: /^sc-[a-zA-Z0-9]+$/ },

  // CSS Modules (webpack default):  styles_container__a1b2c
  { label: 'css-modules', pattern: /^[a-zA-Z]+_[a-zA-Z]+__[a-z0-9]+$/ },

  // Generic hash-based classes generated by bundlers:  a-b1c2d3e4, xy-ab12cd34ef
  // Pattern: 1-4 lowercase prefix + dash + 6-12 alphanumeric hash.
  // The hash portion must contain at least one digit to distinguish from
  // semantic class names like "main-content" or "text-white".
  // Requires 6+ chars in the hash to avoid false positives with Tailwind
  // breakpoint classes like "xl-1a2b3c4d" — though known Tailwind
  // breakpoint prefixes (sm, md, lg, xl, 2xl) are also whitelisted below.
  { label: 'generic-hash', pattern: /^[a-z]{1,4}-(?=[a-z0-9]*[0-9])[a-z0-9]{6,12}$/ },
];

// ---------------------------------------------------------------------------
// Tags that should never contribute innerText to their parent snapshot node.
// These either contain enormous amounts of text (script/style) or have their
// own semantic representation (SVG).
// ---------------------------------------------------------------------------

const IGNORED_TEXT_TAGS = new Set([
  'SCRIPT', 'STYLE', 'NOSCRIPT', 'SVG', 'CANVAS', 'VIDEO', 'AUDIO',
  'IFRAME', 'OBJECT', 'EMBED', 'TEMPLATE',
]);

// Tags whose immediate text content is semantically meaningful and should
// be captured on the node itself.
const INLINE_TEXT_TAGS = new Set([
  'A', 'ABBR', 'B', 'BDI', 'BDO', 'BUTTON', 'CITE', 'CODE', 'DATA',
  'DD', 'DEL', 'DFN', 'DT', 'EM', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6',
  'I', 'INS', 'KBD', 'LABEL', 'LI', 'MARK', 'OPTION', 'P', 'PRE', 'Q',
  'RP', 'RT', 'RUBY', 'S', 'SAMP', 'SMALL', 'SPAN', 'STRONG', 'SUB',
  'SUP', 'TD', 'TH', 'TEXTAREA', 'TIME', 'U', 'VAR',
]);

// ---------------------------------------------------------------------------
// Viewport Intersection
// ---------------------------------------------------------------------------

/**
 * Returns true if the element's bounding box intersects the current viewport
 * and has non-trivial size (both width and height >= MIN_ELEMENT_SIZE).
 *
 * We use `getBoundingClientRect()` which is synchronous and gives us the
 * element's position relative to the viewport — exactly what we need.
 */
export function isInViewport(element: Element): boolean {
  const rect = element.getBoundingClientRect();

  // Filter out zero-size or near-zero-size elements.
  if (rect.width < MIN_ELEMENT_SIZE || rect.height < MIN_ELEMENT_SIZE) {
    return false;
  }

  // Check intersection with viewport rectangle [0, 0, innerWidth, innerHeight].
  return (
    rect.bottom >= 0 &&
    rect.right >= 0 &&
    rect.top <= window.innerHeight &&
    rect.left <= window.innerWidth
  );
}

// ---------------------------------------------------------------------------
// CSS Rot Stripping
// ---------------------------------------------------------------------------

/** Known Tailwind responsive breakpoint prefixes — never flag these as CSS rot. */
const TAILWIND_BREAKPOINTS = new Set(['sm', 'md', 'lg', 'xl', '2xl']);

/**
 * Returns true if a class name looks like a Tailwind breakpoint class
 * (e.g. "xl-something") which should never be treated as CSS rot.
 */
function isTailwindBreakpointClass(cls: string): boolean {
  const dashIndex = cls.indexOf('-');
  if (dashIndex <= 0) return false;
  const prefix = cls.slice(0, dashIndex);
  return TAILWIND_BREAKPOINTS.has(prefix);
}

/**
 * Filters a list of CSS class names, removing those that match known
 * auto-generated / hashed patterns ("CSS rot").
 *
 * Returns only the meaningful, human-authored class names.
 */
export function stripCssRot(classNames: string[]): string[] {
  return classNames.filter((cls) => {
    // Whitelist known Tailwind breakpoint prefixes
    if (isTailwindBreakpointClass(cls)) return true;

    for (const { pattern } of CSS_ROT_PATTERNS) {
      if (pattern.test(cls)) {
        return false;
      }
    }
    return true;
  });
}

/**
 * Returns true if a single class name matches any CSS rot pattern.
 * Tailwind breakpoint classes are excluded from CSS rot detection.
 */
export function isCssRot(className: string): boolean {
  if (isTailwindBreakpointClass(className)) return false;

  for (const { pattern } of CSS_ROT_PATTERNS) {
    if (pattern.test(className)) {
      return true;
    }
  }
  return false;
}

// ---------------------------------------------------------------------------
// Text Truncation
// ---------------------------------------------------------------------------

/**
 * Truncates a string to at most `maxChars` characters.  If truncated, an
 * ellipsis marker is appended to signal downstream consumers that the text
 * was cut off.
 *
 * Attempts to break at word boundaries when possible so we do not cut mid-word.
 */
export function truncateText(text: string, maxChars: number = MAX_TEXT_LENGTH): string {
  if (text.length <= maxChars) {
    return text;
  }

  // Try to find a word boundary (space, newline) near the limit.
  const truncated = text.slice(0, maxChars);
  const lastSpace = truncated.lastIndexOf(' ');

  // If the last space is reasonably close to the limit (within 20% from end),
  // break there for cleaner output.  Otherwise just use the hard limit.
  if (lastSpace > maxChars * 0.8) {
    return truncated.slice(0, lastSpace) + '...';
  }

  return truncated + '...';
}

// ---------------------------------------------------------------------------
// Table Truncation
// ---------------------------------------------------------------------------

/**
 * Given a `<table>` element, builds a DomNode tree that includes at most
 * `maxRows` visible rows.  This prevents huge data tables from bloating
 * the snapshot.
 *
 * Strategy:
 *   - Always include `<thead>` / `<tfoot>` rows.
 *   - For `<tbody>` (or direct `<tr>` children), include only the first
 *     `maxRows` rows that are visible in the viewport.
 *   - If rows were truncated, append a synthetic marker node.
 */
export function truncateTable(
  table: HTMLTableElement,
  maxRows: number = MAX_TABLE_ROWS,
): DomNode {
  const node = extractNodeInfo(table);
  node.children = [];

  // Collect all row-containing sections (<thead>, <tbody>, <tfoot>, or loose <tr>).
  const sections = Array.from(table.children);
  let visibleBodyRowCount = 0;
  let totalBodyRowCount = 0;

  for (const section of sections) {
    if (!(section instanceof HTMLElement)) continue;

    const sectionTag = section.tagName.toUpperCase();

    if (sectionTag === 'THEAD' || sectionTag === 'TFOOT') {
      // Always include head/foot — they contain column headers/summaries.
      const sectionNode = extractNodeInfo(section);
      sectionNode.children = [];
      for (const row of Array.from(section.children)) {
        if (row instanceof HTMLTableRowElement) {
          sectionNode.children.push(buildRowNode(row));
        }
      }
      node.children.push(sectionNode);
    } else if (sectionTag === 'TBODY') {
      const bodyNode = extractNodeInfo(section);
      bodyNode.children = [];

      for (const row of Array.from(section.children)) {
        if (!(row instanceof HTMLTableRowElement)) continue;

        // Skip invisible rows (display:none or visibility:hidden) from the count
        try {
          const rowStyle = window.getComputedStyle(row);
          if (rowStyle.display === 'none' || rowStyle.visibility === 'hidden') {
            continue;
          }
        } catch {
          // getComputedStyle can throw for detached elements; include the row
        }

        totalBodyRowCount++;

        if (visibleBodyRowCount < maxRows && isInViewport(row)) {
          bodyNode.children.push(buildRowNode(row));
          visibleBodyRowCount++;
        }
      }

      node.children.push(bodyNode);
    } else if (sectionTag === 'TR') {
      // Loose <tr> directly under <table> (non-standard but common).
      totalBodyRowCount++;
      if (visibleBodyRowCount < maxRows && isInViewport(section as HTMLTableRowElement)) {
        node.children.push(buildRowNode(section as HTMLTableRowElement));
        visibleBodyRowCount++;
      }
    } else if (sectionTag === 'CAPTION' || sectionTag === 'COLGROUP') {
      // Include caption and colgroup as-is.
      node.children.push(extractNodeInfo(section));
    }
  }

  // If we truncated rows, add a marker so consumers know the data is partial.
  if (visibleBodyRowCount < totalBodyRowCount) {
    node.children.push({
      tag: '#truncated',
      innerText: `[${totalBodyRowCount - visibleBodyRowCount} more rows truncated]`,
    });
  }

  return node;
}

/**
 * Build a DomNode for a single table row, including its cells.
 */
function buildRowNode(row: HTMLTableRowElement): DomNode {
  const rowNode = extractNodeInfo(row);
  rowNode.children = [];

  for (const cell of Array.from(row.cells)) {
    const cellNode = extractNodeInfo(cell);
    const text = getDirectText(cell);
    if (text) {
      cellNode.innerText = truncateText(text);
    }
    rowNode.children.push(cellNode);
  }

  return rowNode;
}

// ---------------------------------------------------------------------------
// Semantic Info Extraction
// ---------------------------------------------------------------------------

/**
 * Extracts semantic information from a DOM Element into a DomNode.
 *
 * This is the core mapping from browser DOM -> AgentHandover snapshot format.
 * We capture everything that an agent would need to identify and interact
 * with the element, while ignoring implementation details like generated
 * class names.
 */
export function extractNodeInfo(element: Element): DomNode {
  const tag = element.tagName.toLowerCase();
  const node: DomNode = { tag };

  // ARIA role — explicit or implicit.
  const role = element.getAttribute('role');
  if (role) {
    node.role = role;
  }

  // ARIA label — the accessible name.
  const ariaLabel = element.getAttribute('aria-label');
  if (ariaLabel) {
    node.ariaLabel = ariaLabel;
  }

  // Accessible name via aria-labelledby (resolve to text).
  if (!ariaLabel) {
    const labelledBy = element.getAttribute('aria-labelledby');
    if (labelledBy) {
      const labelElement = element.ownerDocument.getElementById(labelledBy);
      if (labelElement) {
        const labelText = labelElement.textContent?.trim();
        if (labelText) {
          node.name = truncateText(labelText);
        }
      }
    }
  }

  // data-testid (common in React, testing-library).
  const testId =
    element.getAttribute('data-testid') ||
    element.getAttribute('data-test-id') ||
    element.getAttribute('data-cy');
  if (testId) {
    node.testId = testId;
  }

  // Bounding box in viewport coordinates.
  const rect = element.getBoundingClientRect();
  if (rect.width > 0 && rect.height > 0) {
    node.bbox = {
      x: Math.round(rect.x),
      y: Math.round(rect.y),
      width: Math.round(rect.width),
      height: Math.round(rect.height),
    };
  }

  // Interactive element state.
  if (element instanceof HTMLInputElement) {
    node.state = {
      enabled: !element.disabled,
      checked: element.checked,
    };
    // For inputs, capture the type as part of tag for better semantics.
    if (element.type && element.type !== 'text') {
      node.tag = `input[type=${element.type}]`;
    }
    // Capture placeholder as name if no aria-label.
    if (!node.ariaLabel && element.placeholder) {
      node.name = element.placeholder;
    }
    // Capture value for non-password inputs — use higher limit for
    // user-produced text (most valuable for workflow learning).
    if (element.type !== 'password' && element.value) {
      node.innerText = truncateText(element.value, MAX_INPUT_TEXT_LENGTH);
    }
  } else if (element instanceof HTMLSelectElement) {
    node.state = {
      enabled: !element.disabled,
    };
    // Capture selected option text.
    const selected = element.options[element.selectedIndex];
    if (selected) {
      node.state.selected = true;
      node.innerText = selected.text;
    }
  } else if (element instanceof HTMLButtonElement) {
    node.state = {
      enabled: !element.disabled,
    };
  } else if (element instanceof HTMLTextAreaElement) {
    node.state = {
      enabled: !element.disabled,
    };
    if (!node.ariaLabel && element.placeholder) {
      node.name = element.placeholder;
    }
    // Capture textarea value — user-produced text, use higher limit.
    if (element.value) {
      node.innerText = truncateText(element.value, MAX_INPUT_TEXT_LENGTH);
    }
  }

  // For elements with aria-checked or aria-selected (custom widgets).
  const ariaChecked = element.getAttribute('aria-checked');
  if (ariaChecked !== null) {
    if (!node.state) node.state = {};
    node.state.checked = ariaChecked === 'true';
  }

  const ariaSelected = element.getAttribute('aria-selected');
  if (ariaSelected !== null) {
    if (!node.state) node.state = {};
    node.state.selected = ariaSelected === 'true';
  }

  const ariaDisabled = element.getAttribute('aria-disabled');
  if (ariaDisabled !== null) {
    if (!node.state) node.state = {};
    node.state.enabled = ariaDisabled !== 'true';
  }

  // Meaningful classes (after stripping CSS rot).
  const allClasses = Array.from(element.classList);
  if (allClasses.length > 0) {
    const meaningful = stripCssRot(allClasses);
    if (meaningful.length > 0) {
      // Store meaningful classes as a name hint when no other name is available.
      if (!node.name && !node.ariaLabel && !node.testId) {
        node.name = meaningful.join(' ');
      }
    }
  }

  return node;
}

// ---------------------------------------------------------------------------
// Text Helpers
// ---------------------------------------------------------------------------

/**
 * Gets the direct text content of an element, excluding text from child
 * elements.  This prevents parent nodes from duplicating all descendant text.
 */
function getDirectText(element: Element): string {
  let text = '';
  for (const child of Array.from(element.childNodes)) {
    if (child.nodeType === Node.TEXT_NODE) {
      text += child.textContent ?? '';
    }
  }
  return text.trim();
}

// ---------------------------------------------------------------------------
// DOM Tree Walker (with Shadow DOM Piercing)
// ---------------------------------------------------------------------------

/**
 * Mutable counter shared across an entire walkDOM traversal to enforce
 * the MAX_NODE_COUNT limit.  Using an object allows pass-by-reference
 * semantics through the recursive calls.
 */
export interface NodeCounter {
  count: number;
  truncated: boolean;
}

/**
 * Recursively walks the DOM tree starting from `node`, building a DomNode
 * tree that includes only viewport-visible elements.
 *
 * Shadow DOM piercing: when an element has an open `shadowRoot`, we recurse
 * into it and mark the resulting children with `isShadowRoot: true`.
 *
 * @param node     The DOM node to process.
 * @param depth    Current recursion depth (capped at MAX_TREE_DEPTH).
 * @param counter  Shared counter tracking total nodes produced (for MAX_NODE_COUNT).
 * @returns        A DomNode if the element is visible and relevant, or null.
 */
export function walkDOM(
  node: Node,
  depth: number = 0,
  counter: NodeCounter = { count: 0, truncated: false },
): DomNode | null {
  // Guard against infinite recursion.
  if (depth > MAX_TREE_DEPTH) {
    return null;
  }

  // Guard against oversized snapshots.
  if (counter.count >= MAX_NODE_COUNT) {
    counter.truncated = true;
    return null;
  }

  // We only process Element nodes (skip text nodes, comments, etc.).
  if (!(node instanceof Element)) {
    return null;
  }

  const element = node;
  const tag = element.tagName.toUpperCase();

  // Skip elements that should never appear in the snapshot.
  if (IGNORED_TEXT_TAGS.has(tag)) {
    return null;
  }

  // Skip hidden elements (display:none, visibility:hidden, or hidden attribute).
  if (element.hasAttribute('hidden')) {
    return null;
  }

  // Check visibility via computed style — only if the element is attached
  // to the document (otherwise getComputedStyle will return empty).
  if (element.isConnected) {
    try {
      const style = window.getComputedStyle(element);
      if (style.display === 'none' || style.visibility === 'hidden') {
        return null;
      }
    } catch {
      // getComputedStyle can throw in edge cases (detached elements,
      // cross-origin iframes); we silently skip the check.
    }
  }

  // Viewport check — skip leaf elements completely outside the viewport.
  // For container elements (those with children), we always recurse into
  // their children even if the container itself is off-viewport, because
  // children may be positioned independently and still be visible.
  const rect = element.getBoundingClientRect();
  const hasNonTrivialSize = rect.width >= MIN_ELEMENT_SIZE && rect.height >= MIN_ELEMENT_SIZE;

  if (hasNonTrivialSize && !isInViewport(element) && element.children.length === 0) {
    return null; // Skip leaf nodes outside viewport
  }
  // For containers: continue to process children even if container is off-viewport

  // Special handling for tables.
  if (element instanceof HTMLTableElement) {
    return truncateTable(element);
  }

  // Build the DomNode for this element.
  const domNode = extractNodeInfo(element);
  counter.count++;

  // Capture inline text for leaf-like elements.
  if (INLINE_TEXT_TAGS.has(tag)) {
    const text = getDirectText(element);
    if (text && !domNode.innerText) {
      domNode.innerText = truncateText(text);
    }
  }

  // Collect children: first from shadow root (if any), then from light DOM.
  const children: DomNode[] = [];

  // Pierce Shadow DOM: if the element has an open shadowRoot, walk its children.
  if (element.shadowRoot) {
    for (const shadowChild of Array.from(element.shadowRoot.children)) {
      if (counter.count >= MAX_NODE_COUNT) {
        counter.truncated = true;
        break;
      }
      const childNode = walkDOM(shadowChild, depth + 1, counter);
      if (childNode) {
        childNode.isShadowRoot = true;
        children.push(childNode);
      }
    }
  }

  // Walk light DOM children.
  for (const child of Array.from(element.children)) {
    if (counter.count >= MAX_NODE_COUNT) {
      counter.truncated = true;
      break;
    }

    // Skip <slot> elements if we already processed the shadow root —
    // slotted content is already included via the shadow tree.
    if (element.shadowRoot && child.tagName === 'SLOT') {
      continue;
    }

    const childNode = walkDOM(child, depth + 1, counter);
    if (childNode) {
      children.push(childNode);
    }
  }

  if (children.length > 0) {
    domNode.children = children;
  }

  return domNode;
}

// ---------------------------------------------------------------------------
// Main Entry Point
// ---------------------------------------------------------------------------

/**
 * Captures a viewport-bounded DOM snapshot of the current page.
 *
 * The returned tree contains only elements visible within the viewport,
 * with semantic anchors extracted and CSS rot stripped.  Shadow DOM trees
 * are pierced recursively.
 *
 * This is the function called by the content script in response to
 * snapshot requests from the background service worker.
 */
export function captureViewportDOM(): DomNode[] {
  const body = document.body;
  if (!body) {
    return [];
  }

  const counter: NodeCounter = { count: 0, truncated: false };
  const roots: DomNode[] = [];

  for (const child of Array.from(body.children)) {
    if (counter.count >= MAX_NODE_COUNT) {
      counter.truncated = true;
      break;
    }
    const node = walkDOM(child, 0, counter);
    if (node) {
      roots.push(node);
    }
  }

  // Signal to consumers that the snapshot was capped.
  if (counter.truncated) {
    roots.push({
      tag: '#truncated',
      innerText: `[DOM snapshot capped at ${MAX_NODE_COUNT} nodes]`,
    });
  }

  return roots;
}
